import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const LandingFAQ = () => {
  const faqs = [
    {
      question: "What is a lossless lottery?",
      answer: "In a lossless lottery, your deposit (principal) remains safe and withdrawable. Prizes come from the yield generated by staking your TON deposits. You can win without losing your original investment."
    },
    {
      question: "How often are winners drawn?",
      answer: "Currently winners are drawn every 72 hours in continuous epochs. Each epoch selects 1 winners based on their ticket weights and a fair random number generation process. this will may change as the community grows."
    },
    {
      question: "What determines my winning chances?",
      answer: "Your chances depend on: (1) TON deposited (base tickets), (2) Age factor (up to 2x after 30 days), (3) LLL token boost (logarithmic scaling), and (4) veLLL lock bonus (up to 20% extra)."
    },
    {
      question: "Can I withdraw my funds anytime?",
      answer: "Yes! You can withdraw using two methods: Slow withdraw (0% fee, 7-day processing) or Fast withdraw (1% fee, instant processing). Your principal is always safe."
    },
    {
      question: "What is the LLL token used for?",
      answer: "LLL tokens provide: ticket multiplier boosts, governance voting power when locked as veLLL, referral rewards, fee discounts, and the option to claim prizes in LLL (with 7-day vesting or instant with 15% burn)."
    },
    {
      question: "How does the referral system work?",
      answer: "Earn 10% of your referrals' yield: 1% to treasury, 6% from their prize allocation, 3% from new LLL emission. Requires ≥1,000 LLL staked to activate referral rewards."
    },
    {
      question: "Is LLL.SPACE safe and fair?",
      answer: "Yes. The protocol is non-custodial (funds go to tsTON staking), uses commit-reveal + TON randomness for fair RNG, and will undergo security audits. All contract addresses are transparent."
    },
    {
      question: "How do I get started?",
      answer: "Connect your TON wallet (Tonkeeper or Telegram Wallet), deposit TON to join the pool, and you'll automatically be entered in the next draw. Start earning tickets and multipliers immediately!"
    }
  ];

  return (
    <section className="py-20 px-4 bg-background relative overflow-hidden">
            {/* Background effects */}
      <div className="absolute inset-0 opacity-10">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_50%,hsl(var(--neon-yellow))_0%,transparent_50%)]" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_50%,hsl(var(--neon-cyan))_0%,transparent_50%)]" />
      </div>
      <div className="container mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold font-orbitron text-neon-magenta mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Everything you need to know about lossless lottery mechanics, 
            rewards, and getting started with LLL.SPACE.
          </p>
        </div>

        <div className="max-w-4xl mx-auto">
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem 
                key={index} 
                value={`item-${index}`}
                className="bg-surface/30 border border-neon-cyan/20 rounded-lg px-6 backdrop-blur-sm"
              >
                <AccordionTrigger className="text-left hover:text-neon-cyan transition-colors">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};

export default LandingFAQ;